version: '3.5'
services:
#  pathmap-storage-service:
#    image: quay.io/factory2/pathmap-storage-service:latest
#    container_name: storage
#    ports:
#      - "8081:8080"
#    restart: always
#    #volumes:
#    #  - ./storage-service/config:/opt/pathmap-storage-service/config

  zookeeper:
    image: strimzi/kafka:0.19.0-kafka-2.5.0
    command: [
      "sh", "-c",
      "bin/zookeeper-server-start.sh config/zookeeper.properties"
    ]
    ports:
      - "2181:2181"
    environment:
      LOG_DIR: /tmp/logs

  kafka:
    image: strimzi/kafka:0.19.0-kafka-2.5.0
    command: [
      "sh", "-c",
      "bin/kafka-server-start.sh config/server.properties --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT}"
    ]
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      LOG_DIR: "/tmp/logs"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  indy-promote-service:
    image: quay.io/factory2/indy-promote-service:latest
    container_name: promote
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./config:/opt/indy-promote-service/config
      - ./data:/opt/indy-promote-service/data
