# Quarkus will choose application.yaml over application.properties.
quarkus:
    http:
        port: 8080
        read-timeout: 30m
        limits:
          max-body-size: 500M

    # Logging (disable console on prod)
    log:
        level: INFO
        category:
            "org.commonjava.service.promote":
                level: DEBUG
        console:
            level: DEBUG
            enable: true
        file:
            enable: true
            path: "log/promote.log"
            level: DEBUG
            format: "%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n"
            rotation:
                max-backup-index: 5
                max-file-size: 10M
    keycloak:
        policy-enforcer:
            enable: false
    oidc:
        enabled: true
        auth-server-url: "https://localhost:8543/realms/indy"
        client-id: indy
        credentials:
            secret: secret
        tls:
            verification: none
        token:
            issuer: any
            refresh-token-time-skew: 60 # The refresh token time skew, in seconds.

    security:
        auth:
            enabled-in-dev-mode: false

    oidc-client:
        auth-server-url: "keycloak_server_url/realms/pncredhat"
        client-id: your_client_id
        credentials:
            secret: your_secret
        refresh-token-time-skew: 60

    swagger-ui:
        always-include: true

    opentelemetry:
        enabled: true

indy_security:
    enabled: false
    security_bindings_yaml: config/security-bindings.yaml

promote:
    baseDir: "data"
    callbackUri: "callbackUri"
    threadpools:
        promote-runner: 8
        promote-rules-runner: 16
        promote-rules-batch-executor: 16

storage-service-api/mp-rest/url: http://localhost
storage-service-api/mp-rest/scope: javax.inject.Singleton

content-service-api/mp-rest/url: http://localhost
content-service-api/mp-rest/scope: javax.inject.Singleton

repo-service-api/mp-rest/url: http://localhost
repo-service-api/mp-rest/scope: javax.inject.Singleton

kafka:
    bootstrap:
        servers: "localhost:9092"

"%dev":
    quarkus:
        kubernetes-config:
            enabled: false
        oidc:
            enabled: false
        log:
            level: INFO
            category:
                "org.commonjava.service.promote":
                    level: TRACE
            console:
                enable: true
            file:
                enable: true
                path: "/tmp/indy-promote-service.log"
                format: "%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n"
                rotation:
                    max-backup-index: 5
                    max-file-size: 10M
    promote:
        baseDir: "/tmp"
        callbackUri: "callbackUri"

    kafka:
        bootstrap:
            servers: "localhost:9092"

#    mp:
#        messaging:
#            incoming:
#                promote-complete:
#                    connector: smallrye-in-memory
#                    topic: promote-complete

"%test":
    quarkus:
        http:
            test-port: 9091
        oidc:
            enabled: false
    cassandra:
        enabled: true
        host: localhost
        port: 9142
        user: cassandra
        pass: cassandra
        keyspace: promote_tracking
        keyspaceReplicas: 1
        retries:
            read: 3
            write: 3